apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec: 
  serviceName: statefulset-service
  replicas: 4
  selector: 
    matchLabels:
      app: first-todolist
  template:
    metadata:
      labels:
        app: first-todolist
    spec:
      containers:
      - name: todolist
        image: harness/todolist-sample:latest
        ports:
        - containerPort: 8080