apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
      version: "1.0"
  template:
    metadata:
      labels:
        app: guestbook
        version: "1.0"
    spec:
      containers:
      - name: guestbook
        image: ibmcom/guestbook:v1
        ports:
        - containerPort: 3000