apiVersion: v1
kind: Service
metadata:
  name: HomeWork-service
spec:
  selector:
    app: HomeWork-stateful 
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32101
  type: NodePort
